Resources:
    Table:
      Type: AWS::DynamoDB::Table
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: Timestamp
            AttributeType: S
          - 
            AttributeName: County
            AttributeType: S
        KeySchema: 
          - 
            AttributeName: Timestamp
            KeyType: HASH
          - 
            AttributeName: County
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.TABLE_NAME}
        Tags:
          - 
            Key: Application
            Value: ${self:provider.environment.APPLICATION}

